Repository WGBH-MLA/AAPB2, pull requests merged in 2024-07, with the labels that each got.

#2762 Adds script to parse apache logs looking for bad bots
  config/environments/production.rb
  scripts/lib/apache_log_parser.rb
Labels: production 🎭

#2746 🗺 Station Map
  app/assets/javascripts/map.js
  app/assets/javascripts/states.js
  app/assets/stylesheets/globals/header.css.scss
  app/assets/stylesheets/map.css
  app/views/home/_map.html.erb
  app/views/home/_orgs_map.html.erb
  app/views/home/show.html.erb
  app/views/organizations/index.html.erb
  app/views/organizations/md/1347.md
  app/views/organizations/md/1889.md
  app/views/organizations/md/UHouston.md
  cmless.py
  config/initializers/assets.rb
  public/assets/.sprockets-manifest-3c099292be953ea65d05328a1f058a9b.json
  public/data/orgs.json
  public/data/us-states.json
  stations.json
Labels: feature request 🧚, enhancement ➕

#2809 🌎 Fixes map asset location
  app/views/home/_map.html.erb
  config/initializers/assets.rb
  public/data/map.css
  public/data/map.js
  public/data/states.js
Labels: bug 🐛, production 🎭
